#!/bin/bash
echo ""
echo "  🤖 Git-Agent — The repo IS the agent"
echo "  ─────────────────────────────────────"
echo ""
echo "  Quick start:"
echo "    1. Read CLAUDE.md for full onboarding guide"
echo "    2. Set up Cloudflare: npx wrangler login"
echo "    3. Add API keys: npx wrangler secret put DEEPSEEK_API_KEY"
echo "    4. Deploy: npx wrangler deploy"
echo "    5. Or run locally: npx wrangler dev"
echo ""
echo "  Interactive TUI (open terminal manually):"
echo "    npm start"
echo ""
echo "  Agent mode (autonomous coding):"
echo "    npm run agent"
echo ""
